project:
  type: website
  output-dir: docs

website:
  title: "The Spotted Ape"
  search: false
  navbar: false 

format:
  html:
    page-layout: custom
    toc: false
    minimal: true
    css: theme.scss
    include-in-header: head.html
    include-before-body: navbar.html
    include-after-body: footer.html
    template-partials:
      - title-block.html